language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

services:
  - redis-server
  - rabbitmq

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - pecl install amqp
  - php -m
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
# core framework:
  - travis_retry composer install --prefer-dist --no-interaction

before_script:

script:
  - vendor/bin/codecept run
